### ISSUE TITLE
[minor]

### ISSUE THREAD

**Issue by ccforbes** [wochen96/freebies#17]
**Describe the minor issue**
Inputting a wrong file for photo in the "New Post"

**To Reproduce**
1. Login
2. Click on 'New Post'
3. Submit a non photo file for photo file
4. Submit post
5. The post doesn't show up, but the post was presumed to be "accept"

**Expected behavior**
Any feedback that says the file is not valid, post not accepted

**Screenshots**

**Device Used:**
 - Dell XPS 15
**Additional context**

**Comment by tran6388-1672747** [comment]
# Real issue

I have fixed the issue with the image, Now the users can only enter file that are image with end in .png or .jpg or .jpeg.

link commit: https://github.com/wochen96/freebies/commit/f456daac5d6c255f7d26b75902847d0cb8362a31
