### ISSUE TITLE
[minor] Can create freebies without inputting details

### ISSUE THREAD

**Issue by lockheedmartian** [wochen96/freebies#18]
**Describe the minor issue**
A user can make limited posts by filling all text fields with whitespace (except the date field). This is a problem as user's can post freebies with no details, just images.

**To Reproduce**
Make a new post
Fill in all text fields with whitespace (by holding down spacebar)
Submit post

**Expected behavior**
Should throw error when trying to submit post with pure whitespace in the input fields.

**Comment by tran6388-1672747** [comment]
# Real failure

I have fixed that now the user can not enter text field with only space. The text fields now require some character to be valid. But, I have not put in the check for any special character like "*" or "_". I presume these character are valid.

commit link: https://github.com/wochen96/freebies/commit/f456daac5d6c255f7d26b75902847d0cb8362a31
