### ISSUE TITLE
[minor] Downvote and upvote amount doesn't work/match 

### ISSUE THREAD

**Issue by Aimee0103wu** [wochen96/freebies#21]
**Describe the minor issue**
When there are multiple downvotes, if you click downvote first and then click upvote, more than one count for downvotes get taken down
**To Reproduce**
1. Go to the site
2. Log in
3. Click on one of the freebies cards that has more than one downvotes
4. click on downvote first
5. then click on upvote
6. See error: more than one downvotes get taken down or no downvote gets taken down.

**Expected behavior**
I expect only one downvote gets taken down and add one more upvote to the vote.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-12-05 at 5 08 03 PM" src="https://user-images.githubusercontent.com/46922678/70296254-c116f400-179e-11ea-9600-acb8e846d802.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 5 07 34 PM" src="https://user-images.githubusercontent.com/46922678/70296255-c116f400-179e-11ea-822c-683a5f531242.png">

**Device Used:**
 - Device: MacBook Pro
 - Browser chrome

**Additional context**

**Comment by tran6388-1672747** [comment]
# duplicate

#19
