### ISSUE TITLE
[minor] No feedback when searching for a freebie that doesn't exist

### ISSUE THREAD

**Issue by tfpenner** [wochen96/freebies#22]
**Describe the minor issue**
I am not told why my search query doesn't bring up any results

**To Reproduce**
1. Go to the search for freebies search field at the top of the screen
2. Enter a string that you are confident won't have results, such as "34243dd1"

**Expected behavior**
There should be an alert or text that states that there are no freebies related to "34243dd1".

*Image*
This occurs after search
<img width="1264" alt="Screen Shot 2019-12-05 at 5 14 41 PM" src="https://user-images.githubusercontent.com/53621324/70288626-0b8c7680-1787-11ea-9255-f7c10a1dd3f8.png">

**Device Used:**
Chrome Desktop Browser
**Additional context**

**Comment by tran6388-1672747** [comment]
# Real failure

I have put in an alert to show the user that if there is no search results.

commit link: https://github.com/wochen96/freebies/commit/d0e8769054c7352a26191a56dc8448283b9d7444
