### ISSUE TITLE
[minor] Search empty string returns all events in the database

### ISSUE THREAD

**Issue by albertli354** [wochen96/freebies#23]
**Describe the minor issue**
When I entering nothing and click the search button, the search result returns all the events. I think it is a better practice to alert users and not showing all events in the database. 

**To Reproduce**
1. Log in to the website. 
2. Click the "search" button
3. The search result page returns all the events. 

**Expected behavior**
The website should show an alert when user searching nothing, and not return all the events to users. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26781751/70287094-9f0f7880-1782-11ea-898f-2249039b3e47.png)

**Device Used:**
 - Device: MacBook Pro
 - Browser: chrom

**Comment by tran6388-1672747** [comment]
# Not real failure

We appreciate the feedback from the user. But, we do not think this is a failure nor we want to fix this. Although this is bad practice to show the user all the results in the database with empty string search, we want to give the users more choice if there is no search match their own. This is one way to achieve this.
