### ISSUE TITLE
[major] Breaks with the clicking of the Nintendo plant icon

### ISSUE THREAD

**Issue by anantr98** [wochen96/freebies#24]
**Describe the minor issue**
Breaks when I click the up vote and down vote on the Nintendo plant icon

**To Reproduce**
1. Go to the Nintendo plant icon and try to click on up vote and down vote multiple times
2. App crashes with an "Unhandled Rejection" 

**Expected behavior**
You are only able to up vote or down vote once 

**Screenshots**

**Device Used:**
Chrome/Safari on a Mac

**Additional context**

**Comment by tran6388-1672747** [comment]
#15 

# duplicate
