### ISSUE TITLE
[minor]Log in issue

### ISSUE THREAD

**Issue by deepforce** [wochen96/freebies#25]
**Describe the minor issue**
Open the log in pop up window but close it finally.

**To Reproduce**
1. Click on 'Log in' button and it shows the Gmail login
2. Close it by clicking on 'x' button

**Expected behavior**
It should not show the error to users

**Screenshots**
![image](https://user-images.githubusercontent.com/10813672/70367591-385b8f00-1856-11ea-9b16-e13f5329f06c.png)

**Device Used:**
 - Device: [Windows]
 - Browser [chrome]

**Comment by wochen96** [comment]
# Real failure

We have solved this issue! We understand that it can be inconvenient for users to close the login screen and the user might want to learn more about the website.

commit link: https://github.com/wochen96/freebies/commit/dd50c8c1f33239e77da06ed363f04796664ce431
