### ISSUE TITLE
[minor] Can create all blank posts

### ISSUE THREAD

**Issue by LeoKwo** [wochen96/freebies#26]
**Describe the minor issue**
The user is able to create all blank posts with no information at all.

**To Reproduce**
1. Login to session
2. Click on 'new post'
3. Select time limit as 'unlimited'
4. Enter space to all blanks
5. Upload a non-image file as image.

**Expected behavior**
I expect it to check for all blank inputs. I expect it to check for the appropriate image file.

**Screenshots**
![Screen Shot 2019-12-07 at 15 41 21](https://user-images.githubusercontent.com/37886365/70381932-0acf1e00-1908-11ea-9703-8b2d73781663.jpg)

**Device Used:**
 - OS: macOS 10.15.1
 - Browser Chrome
 - Version 78.0.3904.108

**Comment by tran6388-1672747** [comment]
# duplicate

#18
