### ISSUE TITLE
[minor] Can upvote and downvote on the same thing

### ISSUE THREAD

**Issue by laurens24** [wochen96/freebies#27]
**Describe the minor issue**
You can both upvote and downvote on the same thing

**To Reproduce**
1. Click an event on the homepage
2. Clicked Down Vote, count increased by 1
3. Clicked Down Vote again, count stayed the same (which is good)
4. Clicked Up Vote, upvote count increased by 1

**Expected behavior**
Can only vote either on upvote or downvote

**Device Used:**
 - Device: Macbook Pro 13"
 - Browser Chrome

**Comment by tran6388-1672747** [comment]
# duplicate

#19
