### ISSUE TITLE
[minor]Have no idea which filter is currently applied

### ISSUE THREAD

**Issue by GarsonYang** [wochen96/freebies#28]
**Describe the minor issue**
Users cannot see which filter is selected and applied

**To Reproduce**
1. Go to the home page
2. Log in
3. Have no idea what are the displayed events and do not know which filter is currently applied

**Expected behavior**
Show that the selected filter button that it's selected

**Rationale**
I got lost when I first visit the website.

**Comment by tran6388-1672747** [comment]
# Not real failure

The filter does high-line with different set around the button, but it's maybe too small to be noticed. So I have change the code to change color of the background to make it more clear

commit link: https://github.com/wochen96/freebies/commit/c9394fdf41b25111868c0813b59371198b736a11
