### ISSUE TITLE
[minor]Empty pop-up window when I'm already logged in

### ISSUE THREAD

**Issue by GarsonYang** [wochen96/freebies#30]
**Describe the minor issue**
When I've already logged in and revisit the website, I have to click on the "log in" button because it's the only entrance. However, it pops up an empty window.

**To Reproduce**
1. Go to the home page.
2. Log in.
3. Go back to the home page.
4. Click on the "Log in" button again.
5. See the empty pop-up window.

**Expected behavior**
Consider to take the user directly to the main portal when detected user's login info or take out the empty pop-up window.

**Comment by wochen96** [comment]
# Real failure

This issue has been solved on the latest commit. We understand that it is confusing for returning users to have a random window pop up.

commit link: https://github.com/wochen96/freebies/commit/dd50c8c1f33239e77da06ed363f04796664ce431
