### ISSUE TITLE
[minor] UX issue

### ISSUE THREAD

**Issue by 3ickey** [wochen96/freebies#31]
**Describe the minor issue**
After I create a post and go to edit to replace the image with a new one, it brakes the link and the image is not displayed.

**To Reproduce**
1. Go to 'New post'
2. Fill out the form with all details including an image
3. Submit form
4. Find post and click on 'Edit"
5. Replace image with a new one
6. See error where the new image is broken

**Expected behavior**
I expected to replace the image without any issue. One use case is that maybe the image was misleading and want to change it so that students are informed properly. 

**Desktop**
 - OS: macOS
 - Browser: Safari

**Additional context**
When you got to view a post the poster's email is displayed to everyone and this could be an ethical issue in the future.

**Comment by tran6388-1672747** [comment]
# duplicate

#18
