### ISSUE TITLE
[minor] Cannot undo upvote/downvote

### ISSUE THREAD

**Issue by alexh5** [wochen96/freebies#32]
**Describe the minor issue**
On a post, there is no option for the user to remove their upvote or downvote. 

**To Reproduce**
1. Click on a post.
2. Click on the upvote button. The count will increase by 1.
3. Click on the upvote button. The count will stay the same.

**Expected behavior**
After clicking the upvote or downvote button a second time, the count should decrease by 1.

This is a problem because if a user accidentally clicks on the upvote/downvote button, the user has no way to remove their vote. If the user has no opinion on the post, they cannot undo their error,  spreading false information.

**Comment by tran6388-1672747** [comment]
# duplicate

#19
