### ISSUE TITLE
[minor] error says to fill all missing fields when start date is later than end date on creation of new event

### ISSUE THREAD

**Issue by Uyedacb** [wochen96/freebies#33]
**Describe the minor issue**
When creating a new event, the pop-up for errors says that all missing fields needs to be filled even though all fields are filled. This occurs when the start date is later than the end date.

**To Reproduce**
1. https://freebiesuw.herokuapp.com/home
2. Click on New Post
3. Fill in all required fields
4. Set start date to be later than end date
5. See error pop-up saying that all fields need to be filled

**Expected behavior**
Expected an error message stating that the start date cannot be later than the end date (as seen when you attempt to edit a post).

Expected to see this error message:
![image](https://user-images.githubusercontent.com/24310183/70474974-6fb18200-1a88-11ea-9f83-80154ff0650d.png)

But got this:
![image](https://user-images.githubusercontent.com/24310183/70475046-92dc3180-1a88-11ea-9163-7adf16ed421b.png)

**Desktop:**
OS: Windows 10
Browser Chrome
Version 78.0.3904.108 (64 bit)

**Additional context**
The error message has a grammar error. Should be "The end time **has** to be later than the start time." rather than **have**. minor error.

**Comment by tran6388-1672747** [comment]
# Not real failure/unreproducible

I have test the code many time and it works like expected. Thus, we can't reproduce the error. From the scene, it look like one field is missing which is the tag.
