### ISSUE TITLE
[major] Unable to create a new post of unlimited time

### ISSUE THREAD

**Issue by poojaram** [wochen96/freebies#34]
**Describe the major issue**
When I try to create a new post of unlimited time - it does not create a new event.

**To Reproduce**
1. Sign in
2. Click on New post
3. Fill out all the details and select the 'Event Time Limit' to be unlimited
4. It does not create the event.

**Expected behavior**
It was supposed to create a new card with the new event created but it does not show up, but I think the reason the default display is set to limited time events!

**Screenshots**

**Device Used:**
 - Device: [e.g. MacBook Pro, iPhone 6]

**Additional context**

**Comment by tran6388-1672747** [comment]
# Not real failure

From the comment, we suspect that the user did create a new event in the "unlimited" section. But when the user click submit, it will create a the event in the "unlimited" section. The page then return to the default which is populating the events in the "limited" section. So, the event did get create, but the user need to click the unlimited button to see it. This is incline with our design and requirement, and it work like we expect.
